### PR TITLE
Making host handling able to pass in protocol and port.

### PR DESCRIPTION
**Pull request by hekaldama**
Realized I removed the warn message when port goes to :80. Not sure if this is okay or not, but desire is to do:

``` bash
smolder host.com:123 test.yml
```

### CODE REVIEW

**Comment by hekaldama** [comment]
I am not sure which way the defaults should go or which one should win. My use case is wanting to do an docker inspect on a running container, get the dynamic port assigned to it, and then run the smolder.yml from the image against itself. Am I thinking about this in the wrong way? Kind of like:

``` bash
./smolder http://localhost:$(\
    docker inspect app_to_test | grep HostPort | sed "s/[^0-9]//g"\
) <(\
    docker exec app_to_test cat smolder.yml
)
```

may have syntax errors.

**Comment by hekaldama** [comment]
I see port and protocol handling are in two places (so far):

https://github.com/sky-shiny/smolder/blob/master/smolder#L118-L128

and

https://github.com/sky-shiny/smolder/blob/master/charcoal/charcoal.py#L53-L58

Which is the proper place?

**Comment by sky-shiny** [comment]
Fixes have been merged that should allow the host argument to override defaults for protocol and port.  It is important to note, that if protocol or port are specified in a test the test will "win".  

I will open a new ticket to separate out the default and override handling into an import with more unit testing which you have demonstrated here.

**Comment by mcameron** [comment]
Screen shot attached demonstrating sending the port via the host argument.  Closing this ticket.  Please reopen if I've missed something or the --port argument is required. 

Unit tests and improved supportability and readability fixes for input handling/defaults/overrides here:
https://github.com/sky-shiny/smolder/issues/46

screen shot 2015-10-25 at 12 29 58

**Pull request closed without merging**
